"""initial_migration

Revision ID: 5498edf5c956
Revises:
Create Date: 2025-11-12 23:20:16.346868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5498edf5c956"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=150), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=150), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "events",
        sa.Column("ufcstats_id", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("organization", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("poster_url", sa.String(length=500), nullable=True),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=150), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=150), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_ufcstats_id"), "events", ["ufcstats_id"], unique=True
    )
    op.create_table(
        "fighters",
        sa.Column("ufcstats_id", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=350), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column("last_organization_fight", sa.String(length=50), nullable=True),
        sa.Column("actual_weight_class", sa.String(length=50), nullable=True),
        sa.Column("fighting_style", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", sa.TIMESTAMP(), nullable=True),
        sa.Column("stance", sa.String(length=50), nullable=True),
        sa.Column("weight_lbs", sa.Float(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("reach_cm", sa.Float(), nullable=True),
        sa.Column("striking", sa.Integer(), nullable=True),
        sa.Column("grappling", sa.Integer(), nullable=True),
        sa.Column("defense", sa.Integer(), nullable=True),
        sa.Column("stamina", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.Column("strategy", sa.Integer(), nullable=True),
        sa.Column("slpm", sa.Float(), nullable=True),
        sa.Column("str_acc", sa.Float(), nullable=True),
        sa.Column("sapm", sa.Float(), nullable=True),
        sa.Column("str_def", sa.Float(), nullable=True),
        sa.Column("td_avg", sa.Float(), nullable=True),
        sa.Column("td_acc", sa.Float(), nullable=True),
        sa.Column("td_def", sa.Float(), nullable=True),
        sa.Column("sub_avg", sa.Float(), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("losses", sa.Integer(), nullable=True),
        sa.Column("draws", sa.Integer(), nullable=True),
        sa.Column("ko_wins", sa.Integer(), nullable=True),
        sa.Column("submission_wins", sa.Integer(), nullable=True),
        sa.Column("cartel", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("is_real", sa.Boolean(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=150), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=150), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fighters_name"), "fighters", ["name"], unique=False)
    op.create_index(
        op.f("ix_fighters_ufcstats_id"), "fighters", ["ufcstats_id"], unique=True
    )
    op.create_table(
        "fight_simulations",
        sa.Column("fighter1_id", sa.UUID(), nullable=False),
        sa.Column("fighter2_id", sa.UUID(), nullable=False),
        sa.Column("winner_id", sa.UUID(), nullable=False),
        sa.Column("result_type", sa.String(length=50), nullable=False),
        sa.Column("rounds", sa.Integer(), nullable=False),
        sa.Column("finish_round", sa.Integer(), nullable=True),
        sa.Column("fighter1_probability", sa.Float(), nullable=False),
        sa.Column("fighter2_probability", sa.Float(), nullable=False),
        sa.Column(
            "simulation_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=150), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=150), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fighter1_id"],
            ["fighters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fighter2_id"],
            ["fighters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fights",
        sa.Column("ufcstats_id", sa.String(length=50), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("fighter1_id", sa.UUID(), nullable=False),
        sa.Column("fighter2_id", sa.UUID(), nullable=False),
        sa.Column("fight_order", sa.Integer(), nullable=False),
        sa.Column("fight_type", sa.String(length=50), nullable=False),
        sa.Column("weight_class", sa.String(length=100), nullable=True),
        sa.Column("rounds", sa.Integer(), nullable=False),
        sa.Column("is_title_fight", sa.Boolean(), nullable=False),
        sa.Column("winner_id", sa.UUID(), nullable=True),
        sa.Column("result_type", sa.String(length=50), nullable=True),
        sa.Column("finish_round", sa.Integer(), nullable=True),
        sa.Column("finish_time", sa.String(length=10), nullable=True),
        sa.Column("method_details", sa.Text(), nullable=True),
        sa.Column("match_time_seconds", sa.Integer(), nullable=True),
        sa.Column("referee", sa.String(length=150), nullable=True),
        sa.Column("fighter1_probability", sa.Float(), nullable=True),
        sa.Column("fighter2_probability", sa.Float(), nullable=True),
        sa.Column(
            "simulation_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("r_kd", sa.Integer(), nullable=True),
        sa.Column("r_sig_str_landed", sa.Integer(), nullable=True),
        sa.Column("r_sig_str_attempted", sa.Integer(), nullable=True),
        sa.Column("r_total_str_landed", sa.Integer(), nullable=True),
        sa.Column("r_total_str_attempted", sa.Integer(), nullable=True),
        sa.Column("r_td_landed", sa.Integer(), nullable=True),
        sa.Column("r_td_attempted", sa.Integer(), nullable=True),
        sa.Column("r_sub_att", sa.Integer(), nullable=True),
        sa.Column("r_ctrl_seconds", sa.Integer(), nullable=True),
        sa.Column("b_kd", sa.Integer(), nullable=True),
        sa.Column("b_sig_str_landed", sa.Integer(), nullable=True),
        sa.Column("b_sig_str_attempted", sa.Integer(), nullable=True),
        sa.Column("b_total_str_landed", sa.Integer(), nullable=True),
        sa.Column("b_total_str_attempted", sa.Integer(), nullable=True),
        sa.Column("b_td_landed", sa.Integer(), nullable=True),
        sa.Column("b_td_attempted", sa.Integer(), nullable=True),
        sa.Column("b_sub_att", sa.Integer(), nullable=True),
        sa.Column("b_ctrl_seconds", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=150), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=150), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fighter1_id"],
            ["fighters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fighter2_id"],
            ["fighters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["fighters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fights_ufcstats_id"), "fights", ["ufcstats_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fights_ufcstats_id"), table_name="fights")
    op.drop_table("fights")
    op.drop_table("fight_simulations")
    op.drop_index(op.f("ix_fighters_ufcstats_id"), table_name="fighters")
    op.drop_index(op.f("ix_fighters_name"), table_name="fighters")
    op.drop_table("fighters")
    op.drop_index(op.f("ix_events_ufcstats_id"), table_name="events")
    op.drop_table("events")
    op.drop_table("users")
    # ### end Alembic commands ###
