"""Add events and fights tables

Revision ID: 56d601f2cbfa
Revises: 7f1310371bab
Create Date: 2025-11-11 23:41:09.767695

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56d601f2cbfa"
down_revision: Union[str, None] = "7f1310371bab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("organization", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("poster_url", sa.String(length=500), nullable=True),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=150), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=150), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fights",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("fighter1_id", sa.UUID(), nullable=False),
        sa.Column("fighter2_id", sa.UUID(), nullable=False),
        sa.Column("fight_order", sa.Integer(), nullable=False),
        sa.Column("fight_type", sa.String(length=50), nullable=False),
        sa.Column("weight_class", sa.String(length=50), nullable=True),
        sa.Column("rounds", sa.Integer(), nullable=False),
        sa.Column("is_title_fight", sa.Boolean(), nullable=False),
        sa.Column("winner_id", sa.UUID(), nullable=True),
        sa.Column("result_type", sa.String(length=50), nullable=True),
        sa.Column("finish_round", sa.Integer(), nullable=True),
        sa.Column("finish_time", sa.String(length=10), nullable=True),
        sa.Column("method_details", sa.Text(), nullable=True),
        sa.Column("fighter1_probability", sa.Float(), nullable=True),
        sa.Column("fighter2_probability", sa.Float(), nullable=True),
        sa.Column(
            "simulation_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=150), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=150), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fighter1_id"],
            ["fighters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fighter2_id"],
            ["fighters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["fighters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fights")
    op.drop_table("events")
    # ### end Alembic commands ###
