"""Add fighters and simulations tables

Revision ID: 7f1310371bab
Revises: 2024110100001
Create Date: 2025-11-11 21:48:03.798168

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7f1310371bab"
down_revision: Union[str, None] = "2024110100001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Não deletar tabelas antigas (customers/products) - podem ser necessárias
    # op.drop_table('customers')
    # op.drop_index('ix_products_external_id', table_name='products')
    # op.drop_table('products')
    op.alter_column(
        "fight_simulations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_index("idx_simulations_fighter1", table_name="fight_simulations")
    op.drop_index("idx_simulations_fighter2", table_name="fight_simulations")
    op.drop_index("idx_simulations_winner", table_name="fight_simulations")
    op.add_column(
        "fighters",
        sa.Column("last_organization_fight", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "fighters",
        sa.Column("actual_weight_class", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "fighters",
        sa.Column("cartel", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.alter_column(
        "fighters",
        "name",
        existing_type=sa.VARCHAR(length=150),
        type_=sa.String(length=350),
        existing_nullable=False,
    )
    op.alter_column(
        "fighters",
        "fighting_style",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "fighters",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_index("idx_fighters_creator", table_name="fighters")
    op.drop_index("idx_fighters_name", table_name="fighters")
    op.drop_index("idx_fighters_organization", table_name="fighters")
    op.drop_index("idx_fighters_weight_class", table_name="fighters")
    op.drop_column("fighters", "organization")
    op.drop_column("fighters", "weight_class")
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.add_column(
        "fighters",
        sa.Column(
            "weight_class", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "fighters",
        sa.Column(
            "organization", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.create_index(
        "idx_fighters_weight_class", "fighters", ["weight_class"], unique=False
    )
    op.create_index(
        "idx_fighters_organization", "fighters", ["organization"], unique=False
    )
    op.create_index("idx_fighters_name", "fighters", ["name"], unique=False)
    op.create_index("idx_fighters_creator", "fighters", ["creator_id"], unique=False)
    op.alter_column(
        "fighters",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "fighters",
        "fighting_style",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "fighters",
        "name",
        existing_type=sa.String(length=350),
        type_=sa.VARCHAR(length=150),
        existing_nullable=False,
    )
    op.drop_column("fighters", "cartel")
    op.drop_column("fighters", "actual_weight_class")
    op.drop_column("fighters", "last_organization_fight")
    op.create_index(
        "idx_simulations_winner", "fight_simulations", ["winner_id"], unique=False
    )
    op.create_index(
        "idx_simulations_fighter2", "fight_simulations", ["fighter2_id"], unique=False
    )
    op.create_index(
        "idx_simulations_fighter1", "fight_simulations", ["fighter1_id"], unique=False
    )
    op.alter_column(
        "fight_simulations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "external_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "description", sa.VARCHAR(length=1000), autoincrement=False, nullable=True
        ),
        sa.Column(
            "category", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("image", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column(
            "review",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("customer_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_by", sa.VARCHAR(length=150), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_by", sa.VARCHAR(length=150), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_by", sa.VARCHAR(length=150), autoincrement=False, nullable=True
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name="products_customer_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="products_pkey"),
    )
    op.create_index(
        "ix_products_external_id", "products", ["external_id"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.Column(
            "password", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "created_by", sa.VARCHAR(length=150), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_by", sa.VARCHAR(length=150), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_by", sa.VARCHAR(length=150), autoincrement=False, nullable=True
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="customers_pkey"),
        sa.UniqueConstraint("email", name="customers_email_key"),
    )
    # ### end Alembic commands ###
